language: cpp
dist: xenial
compiler: clang

branches:
  only:
    - master

stages:
  - name: Fuzzing

jobs:
  include:
#   Unit tests usually goes here
#   - stage: unit-tests
    - stage: Fuzzing
      name: Continuous Fuzzing via Fuzzit
      language: bash
      compiler: clang
      script: ./fuzzit.sh

env:
  global:
    - secure: "maL+z+jqy57F6fJL+4mG44v83dsaedsdqcjztgKwKG2iw7unbfEFHiv9olWp29fdf+IZtcCuy3gLQ5u5qg10t4++M6orKXNrGlstxVMPK9GWraqtyBrY0MK4XLNCbQ14i/AVUfaE2GKzaNb4bsA5uE4Akz/gzJoV0l1FNipdT9APPqVT2q1nExbUtpjXX0IrtMizp3ViF3TAlBUN4jSWdV1R36aj9VvQhV905DKP1tw6RzCDso7+N1R/OKv4WeqN3SmfGdWaVxiI5FDIpbYDjVPs7A5dePMYiZIijqV7/NmClnAM5i4o00WaokPPQGWa9AoyCUpZ/Q0Cw0FayPWpqUyQuytnWokf9+1jE95vSdNOMEeQYbDTMMKm9Qh1cnF+j2A/fohB68yrWgFim/KmsDl8qXx/LexL6HiYd/jO41O1Za3r0TE2RoedZfCVgzEmvebDGGrfu3uqMwRWci7ngqkOOrE3z5DmZkMk2oRuNx+FjTnCvXa4IwqDWrP8D9Vs28EOMlBWQosyJJjLQh2FhrO+12OcqDaH0S0qu3T7lSZVyvjwSi2pqkSZaPzyACPBj/A2sMRU2ka57WUYa9WdLpdviU+b/kwHfyiTA9XPih0d6S6fDGEx/n0Vbt8VR8sPnMVbpNKVNgxL7WlZfBO+y29UpiaGrGYuDDY3jXg006Q="
